### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by pavelsarker996** [lilygeorgescu/3d-super-res-cnn#32]
Dear Mam,
                  I could not find the two datasets mentioned in the paper of yours related to this work.Is there any way you can upload the datasets also?

**Comment by lilygeorgescu** [comment]
Unfortunately, the CH dataset is private and the NAMIC data set was withdraw from the internet by its authors.
I am sorry that I  cannot help you more. I can suggest the IXI data set (MRI) or the Coltea-Lung-CT-100W data set, if you want to perform SR.

**Comment by pavelsarker996** [comment]
It's ok,mam.Thank you for your time 😃
