### ISSUE TITLE
Confirm dataset format?

### ISSUE THREAD

**Issue by ltminnovator** [lilygeorgescu/3d-super-res-cnn#33]
Hello,

I'm hoping to use your code to help produce accurate simulated ultrasound from CT, but my datasets are all in .nii format.

I'd like to confirm how I should be unpacking the CT volumes into images:

1) Unpack the data volume into the original slices
2) Convert each slice back into a standard image format
3) Group consecutive slices by ~64 slices per folder

And then I only need a set of downsampled images for evaluation?

**Comment by lilygeorgescu** [comment]
Hi,

The format requires to have a folder for each 3D images, therefore, we have to save each .nii file that contains a 3d image into a folder (containing 2D slices in the png/jpeg format). I do not thing that you have to group consecutive slices, but to write all the slices in one folder (of course, if you want to have more data, you can split the 3d image into multiple sub-images). 

Yes, you need downsampled images for evaluation, in the same format as the training samples.

Hope, I answered your questions.

Best

**Comment by ltminnovator** [comment]
Thank you, I believe I can prepare our dataset now :)
