### ISSUE TITLE
Can you tell me how to get the data set CH and NAMIC

### ISSUE THREAD

**Issue by LJBLKR** [lilygeorgescu/3d-super-res-cnn#6]
Hello,Can you tell me how to get the data set CH and NAMIC? thanks!

**Comment by lilygeorgescu** [comment]
Ch dataset is private, but you can download the namic dataset from here https://www.insight-journal.org/midas/collection/view/190

**Comment by 1632325673** [comment]
Is this dataset uniaxial or biaxial
